language: groovy
env:
  - TERM: dumb
jdk:
  - oraclejdk7
  - oraclejdk8
before_install:
  - cd ./shiro3
  - chmod +x ./gradlew
script: ./gradlew clean :grails-shiro:test :cli-tests:test :wildcard-realm:integrationTest -q --stacktrace

